//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", ConfigurationName="ServiceReference1.MultiplepdfPort")]
    public interface MultiplepdfPort
    {
        
        // CODEGEN: Generating message contract since the operation forgot is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.forgotResponse1 forgot(ServiceReference1.forgotRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.forgotResponse1> forgotAsync(ServiceReference1.forgotRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sendBatch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.sendBatchResponse1 sendBatch(ServiceReference1.sendBatchRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.sendBatchResponse1> sendBatchAsync(ServiceReference1.sendBatchRequest1 request);
        
        // CODEGEN: Generating message contract since the operation register is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.registerResponse1 register(ServiceReference1.registerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.registerResponse1> registerAsync(ServiceReference1.registerRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getBatchDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getBatchDetailsResponse1 getBatchDetails(ServiceReference1.getBatchDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getBatchDetailsResponse1> getBatchDetailsAsync(ServiceReference1.getBatchDetailsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation validateToken is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.validateTokenResponse1 validateToken(ServiceReference1.validateTokenRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.validateTokenResponse1> validateTokenAsync(ServiceReference1.validateTokenRequest1 request);
        
        // CODEGEN: Generating message contract since the operation changePassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.changePasswordResponse1 changePassword(ServiceReference1.changePasswordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.changePasswordResponse1> changePasswordAsync(ServiceReference1.changePasswordRequest1 request);
        
        // CODEGEN: Generating message contract since the operation editUserDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.editUserDetailsResponse1 editUserDetails(ServiceReference1.editUserDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.editUserDetailsResponse1> editUserDetailsAsync(ServiceReference1.editUserDetailsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUserDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.getUserDetailsResponse1 getUserDetails(ServiceReference1.getUserDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.getUserDetailsResponse1> getUserDetailsAsync(ServiceReference1.getUserDetailsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.loginResponse1 login(ServiceReference1.loginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.loginResponse1> loginAsync(ServiceReference1.loginRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class forgotRequest
    {
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class forgotResponse
    {
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class forgotRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.forgotRequest forgotRequest;
        
        public forgotRequest1()
        {
        }
        
        public forgotRequest1(ServiceReference1.forgotRequest forgotRequest)
        {
            this.forgotRequest = forgotRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class forgotResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.forgotResponse forgotResponse;
        
        public forgotResponse1()
        {
        }
        
        public forgotResponse1(ServiceReference1.forgotResponse forgotResponse)
        {
            this.forgotResponse = forgotResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class sendBatchRequest
    {
        
        private string listJSONField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string listJSON
        {
            get
            {
                return this.listJSONField;
            }
            set
            {
                this.listJSONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class sendBatchResponse
    {
        
        private string downloadPathField;
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string downloadPath
        {
            get
            {
                return this.downloadPathField;
            }
            set
            {
                this.downloadPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.sendBatchRequest sendBatchRequest;
        
        public sendBatchRequest1()
        {
        }
        
        public sendBatchRequest1(ServiceReference1.sendBatchRequest sendBatchRequest)
        {
            this.sendBatchRequest = sendBatchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.sendBatchResponse sendBatchResponse;
        
        public sendBatchResponse1()
        {
        }
        
        public sendBatchResponse1(ServiceReference1.sendBatchResponse sendBatchResponse)
        {
            this.sendBatchResponse = sendBatchResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class registerRequest
    {
        
        private string nameField;
        
        private string emailField;
        
        private string passwordField;
        
        private string confirm_passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string confirm_password
        {
            get
            {
                return this.confirm_passwordField;
            }
            set
            {
                this.confirm_passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class registerResponse
    {
        
        private string tokenField;
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.registerRequest registerRequest;
        
        public registerRequest1()
        {
        }
        
        public registerRequest1(ServiceReference1.registerRequest registerRequest)
        {
            this.registerRequest = registerRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.registerResponse registerResponse;
        
        public registerResponse1()
        {
        }
        
        public registerResponse1(ServiceReference1.registerResponse registerResponse)
        {
            this.registerResponse = registerResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getBatchDetailsRequest
    {
        
        private string userIDField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getBatchDetailsResponse
    {
        
        private string dateCreatedField;
        
        private int fileQuantityField;
        
        private string pathField;
        
        private string timeExpirationField;
        
        private bool stateField;
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int fileQuantity
        {
            get
            {
                return this.fileQuantityField;
            }
            set
            {
                this.fileQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string timeExpiration
        {
            get
            {
                return this.timeExpirationField;
            }
            set
            {
                this.timeExpirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBatchDetailsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.getBatchDetailsRequest getBatchDetailsRequest;
        
        public getBatchDetailsRequest1()
        {
        }
        
        public getBatchDetailsRequest1(ServiceReference1.getBatchDetailsRequest getBatchDetailsRequest)
        {
            this.getBatchDetailsRequest = getBatchDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBatchDetailsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.getBatchDetailsResponse getBatchDetailsResponse;
        
        public getBatchDetailsResponse1()
        {
        }
        
        public getBatchDetailsResponse1(ServiceReference1.getBatchDetailsResponse getBatchDetailsResponse)
        {
            this.getBatchDetailsResponse = getBatchDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class validateTokenRequest
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class validateTokenResponse
    {
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateTokenRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.validateTokenRequest validateTokenRequest;
        
        public validateTokenRequest1()
        {
        }
        
        public validateTokenRequest1(ServiceReference1.validateTokenRequest validateTokenRequest)
        {
            this.validateTokenRequest = validateTokenRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateTokenResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.validateTokenResponse validateTokenResponse;
        
        public validateTokenResponse1()
        {
        }
        
        public validateTokenResponse1(ServiceReference1.validateTokenResponse validateTokenResponse)
        {
            this.validateTokenResponse = validateTokenResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class changePasswordRequest
    {
        
        private string oldPasswordField;
        
        private string newPasswordField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string oldPassword
        {
            get
            {
                return this.oldPasswordField;
            }
            set
            {
                this.oldPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string newPassword
        {
            get
            {
                return this.newPasswordField;
            }
            set
            {
                this.newPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class changePasswordResponse
    {
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.changePasswordRequest changePasswordRequest;
        
        public changePasswordRequest1()
        {
        }
        
        public changePasswordRequest1(ServiceReference1.changePasswordRequest changePasswordRequest)
        {
            this.changePasswordRequest = changePasswordRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.changePasswordResponse changePasswordResponse;
        
        public changePasswordResponse1()
        {
        }
        
        public changePasswordResponse1(ServiceReference1.changePasswordResponse changePasswordResponse)
        {
            this.changePasswordResponse = changePasswordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class editUserDetailsRequest
    {
        
        private string tokenField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class editUserDetailsResponse
    {
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editUserDetailsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.editUserDetailsRequest editUserDetailsRequest;
        
        public editUserDetailsRequest1()
        {
        }
        
        public editUserDetailsRequest1(ServiceReference1.editUserDetailsRequest editUserDetailsRequest)
        {
            this.editUserDetailsRequest = editUserDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editUserDetailsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.editUserDetailsResponse editUserDetailsResponse;
        
        public editUserDetailsResponse1()
        {
        }
        
        public editUserDetailsResponse1(ServiceReference1.editUserDetailsResponse editUserDetailsResponse)
        {
            this.editUserDetailsResponse = editUserDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getUserDetailsRequest
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class getUserDetailsResponse
    {
        
        private string nameField;
        
        private string emailField;
        
        private string userSinceField;
        
        private string userEditedField;
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userSince
        {
            get
            {
                return this.userSinceField;
            }
            set
            {
                this.userSinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string userEdited
        {
            get
            {
                return this.userEditedField;
            }
            set
            {
                this.userEditedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDetailsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.getUserDetailsRequest getUserDetailsRequest;
        
        public getUserDetailsRequest1()
        {
        }
        
        public getUserDetailsRequest1(ServiceReference1.getUserDetailsRequest getUserDetailsRequest)
        {
            this.getUserDetailsRequest = getUserDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDetailsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.getUserDetailsResponse getUserDetailsResponse;
        
        public getUserDetailsResponse1()
        {
        }
        
        public getUserDetailsResponse1(ServiceReference1.getUserDetailsResponse getUserDetailsResponse)
        {
            this.getUserDetailsResponse = getUserDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class loginRequest
    {
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://spring.io/guides/gs-producing-web-service")]
    public partial class loginResponse
    {
        
        private string tokenField;
        
        private string responseField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.loginRequest loginRequest;
        
        public loginRequest1()
        {
        }
        
        public loginRequest1(ServiceReference1.loginRequest loginRequest)
        {
            this.loginRequest = loginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://spring.io/guides/gs-producing-web-service", Order=0)]
        public ServiceReference1.loginResponse loginResponse;
        
        public loginResponse1()
        {
        }
        
        public loginResponse1(ServiceReference1.loginResponse loginResponse)
        {
            this.loginResponse = loginResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MultiplepdfPortChannel : ServiceReference1.MultiplepdfPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MultiplepdfPortClient : System.ServiceModel.ClientBase<ServiceReference1.MultiplepdfPort>, ServiceReference1.MultiplepdfPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MultiplepdfPortClient() : 
                base(MultiplepdfPortClient.GetDefaultBinding(), MultiplepdfPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MultiplepdfPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MultiplepdfPortClient(EndpointConfiguration endpointConfiguration) : 
                base(MultiplepdfPortClient.GetBindingForEndpoint(endpointConfiguration), MultiplepdfPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MultiplepdfPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MultiplepdfPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MultiplepdfPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MultiplepdfPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MultiplepdfPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.forgotResponse1 ServiceReference1.MultiplepdfPort.forgot(ServiceReference1.forgotRequest1 request)
        {
            return base.Channel.forgot(request);
        }
        
        public ServiceReference1.forgotResponse forgot(ServiceReference1.forgotRequest forgotRequest)
        {
            ServiceReference1.forgotRequest1 inValue = new ServiceReference1.forgotRequest1();
            inValue.forgotRequest = forgotRequest;
            ServiceReference1.forgotResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).forgot(inValue);
            return retVal.forgotResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.forgotResponse1> ServiceReference1.MultiplepdfPort.forgotAsync(ServiceReference1.forgotRequest1 request)
        {
            return base.Channel.forgotAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.forgotResponse1> forgotAsync(ServiceReference1.forgotRequest forgotRequest)
        {
            ServiceReference1.forgotRequest1 inValue = new ServiceReference1.forgotRequest1();
            inValue.forgotRequest = forgotRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).forgotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.sendBatchResponse1 ServiceReference1.MultiplepdfPort.sendBatch(ServiceReference1.sendBatchRequest1 request)
        {
            return base.Channel.sendBatch(request);
        }
        
        public ServiceReference1.sendBatchResponse sendBatch(ServiceReference1.sendBatchRequest sendBatchRequest)
        {
            ServiceReference1.sendBatchRequest1 inValue = new ServiceReference1.sendBatchRequest1();
            inValue.sendBatchRequest = sendBatchRequest;
            ServiceReference1.sendBatchResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).sendBatch(inValue);
            return retVal.sendBatchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.sendBatchResponse1> ServiceReference1.MultiplepdfPort.sendBatchAsync(ServiceReference1.sendBatchRequest1 request)
        {
            return base.Channel.sendBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.sendBatchResponse1> sendBatchAsync(ServiceReference1.sendBatchRequest sendBatchRequest)
        {
            ServiceReference1.sendBatchRequest1 inValue = new ServiceReference1.sendBatchRequest1();
            inValue.sendBatchRequest = sendBatchRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).sendBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.registerResponse1 ServiceReference1.MultiplepdfPort.register(ServiceReference1.registerRequest1 request)
        {
            return base.Channel.register(request);
        }
        
        public ServiceReference1.registerResponse register(ServiceReference1.registerRequest registerRequest)
        {
            ServiceReference1.registerRequest1 inValue = new ServiceReference1.registerRequest1();
            inValue.registerRequest = registerRequest;
            ServiceReference1.registerResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).register(inValue);
            return retVal.registerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.registerResponse1> ServiceReference1.MultiplepdfPort.registerAsync(ServiceReference1.registerRequest1 request)
        {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.registerResponse1> registerAsync(ServiceReference1.registerRequest registerRequest)
        {
            ServiceReference1.registerRequest1 inValue = new ServiceReference1.registerRequest1();
            inValue.registerRequest = registerRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).registerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getBatchDetailsResponse1 ServiceReference1.MultiplepdfPort.getBatchDetails(ServiceReference1.getBatchDetailsRequest1 request)
        {
            return base.Channel.getBatchDetails(request);
        }
        
        public ServiceReference1.getBatchDetailsResponse getBatchDetails(ServiceReference1.getBatchDetailsRequest getBatchDetailsRequest)
        {
            ServiceReference1.getBatchDetailsRequest1 inValue = new ServiceReference1.getBatchDetailsRequest1();
            inValue.getBatchDetailsRequest = getBatchDetailsRequest;
            ServiceReference1.getBatchDetailsResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).getBatchDetails(inValue);
            return retVal.getBatchDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getBatchDetailsResponse1> ServiceReference1.MultiplepdfPort.getBatchDetailsAsync(ServiceReference1.getBatchDetailsRequest1 request)
        {
            return base.Channel.getBatchDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getBatchDetailsResponse1> getBatchDetailsAsync(ServiceReference1.getBatchDetailsRequest getBatchDetailsRequest)
        {
            ServiceReference1.getBatchDetailsRequest1 inValue = new ServiceReference1.getBatchDetailsRequest1();
            inValue.getBatchDetailsRequest = getBatchDetailsRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).getBatchDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.validateTokenResponse1 ServiceReference1.MultiplepdfPort.validateToken(ServiceReference1.validateTokenRequest1 request)
        {
            return base.Channel.validateToken(request);
        }
        
        public ServiceReference1.validateTokenResponse validateToken(ServiceReference1.validateTokenRequest validateTokenRequest)
        {
            ServiceReference1.validateTokenRequest1 inValue = new ServiceReference1.validateTokenRequest1();
            inValue.validateTokenRequest = validateTokenRequest;
            ServiceReference1.validateTokenResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).validateToken(inValue);
            return retVal.validateTokenResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.validateTokenResponse1> ServiceReference1.MultiplepdfPort.validateTokenAsync(ServiceReference1.validateTokenRequest1 request)
        {
            return base.Channel.validateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.validateTokenResponse1> validateTokenAsync(ServiceReference1.validateTokenRequest validateTokenRequest)
        {
            ServiceReference1.validateTokenRequest1 inValue = new ServiceReference1.validateTokenRequest1();
            inValue.validateTokenRequest = validateTokenRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).validateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.changePasswordResponse1 ServiceReference1.MultiplepdfPort.changePassword(ServiceReference1.changePasswordRequest1 request)
        {
            return base.Channel.changePassword(request);
        }
        
        public ServiceReference1.changePasswordResponse changePassword(ServiceReference1.changePasswordRequest changePasswordRequest)
        {
            ServiceReference1.changePasswordRequest1 inValue = new ServiceReference1.changePasswordRequest1();
            inValue.changePasswordRequest = changePasswordRequest;
            ServiceReference1.changePasswordResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).changePassword(inValue);
            return retVal.changePasswordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.changePasswordResponse1> ServiceReference1.MultiplepdfPort.changePasswordAsync(ServiceReference1.changePasswordRequest1 request)
        {
            return base.Channel.changePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.changePasswordResponse1> changePasswordAsync(ServiceReference1.changePasswordRequest changePasswordRequest)
        {
            ServiceReference1.changePasswordRequest1 inValue = new ServiceReference1.changePasswordRequest1();
            inValue.changePasswordRequest = changePasswordRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).changePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.editUserDetailsResponse1 ServiceReference1.MultiplepdfPort.editUserDetails(ServiceReference1.editUserDetailsRequest1 request)
        {
            return base.Channel.editUserDetails(request);
        }
        
        public ServiceReference1.editUserDetailsResponse editUserDetails(ServiceReference1.editUserDetailsRequest editUserDetailsRequest)
        {
            ServiceReference1.editUserDetailsRequest1 inValue = new ServiceReference1.editUserDetailsRequest1();
            inValue.editUserDetailsRequest = editUserDetailsRequest;
            ServiceReference1.editUserDetailsResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).editUserDetails(inValue);
            return retVal.editUserDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.editUserDetailsResponse1> ServiceReference1.MultiplepdfPort.editUserDetailsAsync(ServiceReference1.editUserDetailsRequest1 request)
        {
            return base.Channel.editUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.editUserDetailsResponse1> editUserDetailsAsync(ServiceReference1.editUserDetailsRequest editUserDetailsRequest)
        {
            ServiceReference1.editUserDetailsRequest1 inValue = new ServiceReference1.editUserDetailsRequest1();
            inValue.editUserDetailsRequest = editUserDetailsRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).editUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.getUserDetailsResponse1 ServiceReference1.MultiplepdfPort.getUserDetails(ServiceReference1.getUserDetailsRequest1 request)
        {
            return base.Channel.getUserDetails(request);
        }
        
        public ServiceReference1.getUserDetailsResponse getUserDetails(ServiceReference1.getUserDetailsRequest getUserDetailsRequest)
        {
            ServiceReference1.getUserDetailsRequest1 inValue = new ServiceReference1.getUserDetailsRequest1();
            inValue.getUserDetailsRequest = getUserDetailsRequest;
            ServiceReference1.getUserDetailsResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).getUserDetails(inValue);
            return retVal.getUserDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getUserDetailsResponse1> ServiceReference1.MultiplepdfPort.getUserDetailsAsync(ServiceReference1.getUserDetailsRequest1 request)
        {
            return base.Channel.getUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getUserDetailsResponse1> getUserDetailsAsync(ServiceReference1.getUserDetailsRequest getUserDetailsRequest)
        {
            ServiceReference1.getUserDetailsRequest1 inValue = new ServiceReference1.getUserDetailsRequest1();
            inValue.getUserDetailsRequest = getUserDetailsRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).getUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.loginResponse1 ServiceReference1.MultiplepdfPort.login(ServiceReference1.loginRequest1 request)
        {
            return base.Channel.login(request);
        }
        
        public ServiceReference1.loginResponse login(ServiceReference1.loginRequest loginRequest)
        {
            ServiceReference1.loginRequest1 inValue = new ServiceReference1.loginRequest1();
            inValue.loginRequest = loginRequest;
            ServiceReference1.loginResponse1 retVal = ((ServiceReference1.MultiplepdfPort)(this)).login(inValue);
            return retVal.loginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.loginResponse1> ServiceReference1.MultiplepdfPort.loginAsync(ServiceReference1.loginRequest1 request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.loginResponse1> loginAsync(ServiceReference1.loginRequest loginRequest)
        {
            ServiceReference1.loginRequest1 inValue = new ServiceReference1.loginRequest1();
            inValue.loginRequest = loginRequest;
            return ((ServiceReference1.MultiplepdfPort)(this)).loginAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MultiplepdfPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MultiplepdfPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://java.bucaramanga.upb.edu.co/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MultiplepdfPortClient.GetBindingForEndpoint(EndpointConfiguration.MultiplepdfPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MultiplepdfPortClient.GetEndpointAddress(EndpointConfiguration.MultiplepdfPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            MultiplepdfPortSoap11,
        }
    }
}
